#
# See  https://taskfile.dev/installation/
#
# To install to ./bin/task:
#   sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
#
version: '3'

tasks:
  start:
    cmds:
      - docker compose up -d --build
      - task: install
    aliases:
      - st

  play:
    aliases:
      - p
    cmds:
      - docker compose exec operations ansible-playbook /usr/share/operations/playbook.yml {{ .CLI_ARGS }}

  destroy:
    cmds:
      - docker compose kill && docker compose rm -fv

  shell:
    aliases:
      - sh
    cmds:
      - docker compose exec -u platform operations bash

  exec:
    aliases:
      - e
    cmds:
      - docker compose exec -u platform operations {{ .CLI_ARGS }}
