#
# See  https://taskfile.dev/installation/
#
# To install to ./bin/task:
#   sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
#
version: '3'

tasks:
  up:
    desc: Start containers and run playbook.
    cmds:
      - docker compose up -d --build
      - task: playbook

  build:
    desc: Rebuild & restart containers
    cmds:
      - docker compose up -d --build
    aliases:
      - b

  playbook:
    desc: Run ansible-playbook. Pass options after "--".
    aliases: [p]
    cmds:
      - docker compose exec operations ansible-playbook /usr/share/operations/playbook.yml {{ .CLI_ARGS }}

  destroy:
    desc: Destroy the containers and data.
    aliases: [d]
    cmds:
      - docker compose kill && docker compose rm -fv

  shell:
    desc: Launch a shell inside the container.
    aliases: [sh]
    cmds:
      - docker compose exec operations bash

  exec:
    desc: "Execute any command. Example: task exec -- command-to-run"
    aliases: [e]
    cmds:
      - docker compose exec operations {{ .CLI_ARGS }}

  exec-platform:
    desc: "Execute any command as platform user. Example: task exec-platform -- command-to-run"
    aliases: [e]
    cmds:
      - docker compose exec -u platform operations {{ .CLI_ARGS }}
