
# Global runner path. github.yml will copy this dir instead of downloading.
operations_github_runner_path: /usr/share/github-runner
operations_github_runner_version: 2.322.0

# Set here to apply to all runners.
operations_runner_repo_default: operations-project/ansible-collection-site-runner

operations_github_api_token: "{{ lookup('env', 'GITHUB_TOKEN')  }}"
operations_github_runners:
  - runner_repo: operations-project/ansible-collection-site-runner
    # repo_host: https://github.com
    # runner_name: "{{ inventory_hostname }}"
    # runner_path: "runner"
    # api_token: "{{ operations_github_api_token }}"
    # runner_labels: "{{ inventory_hostname }}"
    # runner_user: platform

operations_runner_extra_packages:
  - jq
